Mod4
smellybeagle/DevOps-Course-Starter pull request #7
Opened 2023-09-12 10:41 UTC by smellybeagle

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2023-09-13 14:27 UTC, JackMead requested changes
Nice work, it definitely looks like you've got the structure here but I can't currently see the app running on your managed node so I think there are still some changes to make! I've tried to leave some helpful suggestions below (and definitely important that we remove your credentials and rotate those!) but if anything doesn't make sense then please do reach out and ask

2023-09-13 14:27 UTC, JackMead commented on todoapp.service
> +ExecStart=/home/ec2-user/.local/bin/poetry run flask run --host 0.0.0.0
Putting this here because there's not an obvious place for the comment, but definitely also worth checking in a copy of your playbook! I've pinched the below directly from your Controller
```yml
---
- name: ToDo App
  hosts: webservers
  remote_user: ec2-user

  tasks:
  - name: Install Git
    become: yes
    become_user: root
    package:
      name: "git"
      state: "latest"

  tasks:
  - name: Create a directory
    become: yes
    become_user: root
    ansible.builtin.file:
      path: /opt/todoapp
      owner: ec2-user
      group: ec2-user
      state: directory
      mode: '0777'


  tasks:
  - name: Clone the TO-Do App latest version
    ansible.builtin.git:
      repo: https://github.com/smellybeagle/DevOps-Course-Starter.git
      version: mod4
      dest: /opt/todoapp

  tasks:
- name: Change Dir to /opt/todoapp and run Poetry Install
  ansible.builtin.shell:
    cmd: /home/ec2-user/.local/bin/poetry install
    chdir: /opt/todoapp

  tasks:
  - name: Copy a version of .env
  ansible.builtin.template:
    src: .env.j2
    dest: /opt/tododapp/.env
    group: ec2-user
    setype: .env_t
    mode: 0777

    tasks:
  - name: Copy todoapp.service
  become: yes
  ansible.builtin.template:
    src: /opt/todoapp/todoapp.service
    dest: /etc/systemd/system/todoapp.service
    group: ec2-user
    mode: 0777

    tasks:
  - name: Reload service todo_app
  become: yes
  ansible.builtin.systemd:
    name: todo_app
    daemon_reload: true
    state: reloaded
```

2023-09-13 14:27 UTC, JackMead commented on .env.j2
> +TOKEN="ATTA43e926f02a2de06813db070512611484789561e3f6dfd4eba1539e5b5f32d3ea8B26C75B"
Ah, credentials!

We always want to avoid this, and the moment they're pushed up to GitHub we should treat these as compromised, even if this had been a private repository. There are ways to carefully remove them from the Git tree, but personally I lean towards not trusting that and rotating these - so e.g. [revoke your token here](https://developer.atlassian.com/cloud/trello/guides/rest-api/authorization/#revoking-tokens) and [generate a new one](https://trello.com/app-key) so that we can just accept that they were leaked but are of no value now

Once that's done, the way we would handle this is to set a placeholder like:
```
API_KEY = {{ api_key }}
```
And then requesting those values from the user:
```yml
- name: ToDo App
  hosts: webservers
  vars_prompt:
    - name: api_key
      prompt: What is your Trello API Key?
      private: true

...
```

This way the user inputs those values when they run the playbook, and we can keep the secrets away from the code stored here

2023-09-13 14:27 UTC, JackMead commented on todoapp.service
> +ExecStart=/home/ec2-user/.local/bin/poetry run flask run --host 0.0.0.0
Feedback on the actual playbook:
* `root` should be the default `become` user, so we could remove those `become_user` entries
* It looks like this playbook misses installing Python & Poetry - I know you may have run into the issue with versions so happy to ignore that here, but we would want to bake those in 
* You've fallen into the habit/trap of setting all directories to `0777` which is a bad practice that will definitely frustrate or worry your security teams! 
  * If you want to be fairly permissive, then `0644` is more typical for directories (Read/write for owner, read for everyone) but since we're specifying the owner/group here, maybe we should be more restricted like `0640` - definitely worth testing and checking I haven't missed a permission though!
  * For the files, I don't think any of them should need execute permissions, so similar permissions (`0644` or `0640` should suffice)


Possibly a consequence of my copying, but the indentation also potentially looks out - we want all of our tasks to be part of a single `tasks` array, so rather than:
```yml
  tasks:
  - name: Install Git
    become: yes
...

  tasks:
  - name: Create a directory
    become: yes
...
```

more like:

```yml
  tasks:
  - name: Install Git
    become: yes
...

  - name: Create a directory
    become: yes
...
```
Carefully making sure all the elements (designated with the `-`) are in line

2023-09-14 06:55 UTC, closed without merging

2023-09-14 06:56 UTC, smellybeagle commented
Closed as new items and changes need adding as per Jack's feedback

2023-09-14 07:03 UTC, smellybeagle commented
Hi Jack,
Thank you very much for the feedback, I have incorporated your suggestions and created a new pull request:
https://github.com/smellybeagle/DevOps-Course-Starter/pull/8
I did struggle with the Python install, I have yet to add it this solution but I have tested it with the next module exercise and got it working in my docker image locally, so I know I can do it but I'd rather not break this one again, Alex wouldn't be happy 🙂


Please can you review again so I can merge the changes and proceed to Module 5.


Many Thanks

Lee


________________________________
From: JackMead ***@***.***>
Sent: 13 September 2023 15:27
To: smellybeagle/DevOps-Course-Starter ***@***.***>
Cc: smellybeagle ***@***.***>; Author ***@***.***>
Subject: Re: [smellybeagle/DevOps-Course-Starter] Mod4 (PR #7)


@JackMead requested changes on this pull request.

Nice work, it definitely looks like you've got the structure here but I can't currently see the app running on your managed node so I think there are still some changes to make! I've tried to leave some helpful suggestions below (and definitely important that we remove your credentials and rotate those!) but if anything doesn't make sense then please do reach out and ask

________________________________

In todoapp.service<https://github.com/smellybeagle/DevOps-Course-Starter/pull/7#discussion_r1324587825>:

> @@ -0,0 +1,7 @@
+[Unit]
+Description=My To-Do App
+
+[Service]
+User=ec2-user
+WorkingDirectory=/opt/todoapp
+ExecStart=/home/ec2-user/.local/bin/poetry run flask run --host 0.0.0.0


Putting this here because there's not an obvious place for the comment, but definitely also worth checking in a copy of your playbook! I've pinched the below directly from your Controller

---
- name: ToDo App
  hosts: webservers
  remote_user: ec2-user

  tasks:
  - name: Install Git
    become: yes
    become_user: root
    package:
      name: "git"
      state: "latest"

  tasks:
  - name: Create a directory
    become: yes
    become_user: root
    ansible.builtin.file:
      path: /opt/todoapp
      owner: ec2-user
      group: ec2-user
      state: directory
      mode: '0777'


  tasks:
  - name: Clone the TO-Do App latest version
    ansible.builtin.git:
      repo: https://github.com/smellybeagle/DevOps-Course-Starter.git
      version: mod4
      dest: /opt/todoapp

  tasks:
- name: Change Dir to /opt/todoapp and run Poetry Install
  ansible.builtin.shell:
    cmd: /home/ec2-user/.local/bin/poetry install
    chdir: /opt/todoapp

  tasks:
  - name: Copy a version of .env
  ansible.builtin.template:
    src: .env.j2
    dest: /opt/tododapp/.env
    group: ec2-user
    setype: .env_t
    mode: 0777

    tasks:
  - name: Copy todoapp.service
  become: yes
  ansible.builtin.template:
    src: /opt/todoapp/todoapp.service
    dest: /etc/systemd/system/todoapp.service
    group: ec2-user
    mode: 0777

    tasks:
  - name: Reload service todo_app
  become: yes
  ansible.builtin.systemd:
    name: todo_app
    daemon_reload: true
    state: reloaded

________________________________

In .env.j2<https://github.com/smellybeagle/DevOps-Course-Starter/pull/7#discussion_r1324589209>:

> +API_KEY ="1a14974b67e88e68f859a2f5236feb25"
+TOKEN="ATTA43e926f02a2de06813db070512611484789561e3f6dfd4eba1539e5b5f32d3ea8B26C75B"


Ah, credentials!

We always want to avoid this, and the moment they're pushed up to GitHub we should treat these as compromised, even if this had been a private repository. There are ways to carefully remove them from the Git tree, but personally I lean towards not trusting that and rotating these - so e.g. revoke your token here<https://developer.atlassian.com/cloud/trello/guides/rest-api/authorization/#revoking-tokens> and generate a new one<https://trello.com/app-key> so that we can just accept that they were leaked but are of no value now

Once that's done, the way we would handle this is to set a placeholder like:

API_KEY = {{ api_key }}


And then requesting those values from the user:

- name: ToDo App
  hosts: webservers
  vars_prompt:
    - name: api_key
      prompt: What is your Trello API Key?
      private: true

...

This way the user inputs those values when they run the playbook, and we can keep the secrets away from the code stored here

________________________________

In todoapp.service<https://github.com/smellybeagle/DevOps-Course-Starter/pull/7#discussion_r1324595155>:

> @@ -0,0 +1,7 @@
+[Unit]
+Description=My To-Do App
+
+[Service]
+User=ec2-user
+WorkingDirectory=/opt/todoapp
+ExecStart=/home/ec2-user/.local/bin/poetry run flask run --host 0.0.0.0


Feedback on the actual playbook:

  *   root should be the default become user, so we could remove those become_user entries
  *   It looks like this playbook misses installing Python & Poetry - I know you may have run into the issue with versions so happy to ignore that here, but we would want to bake those in
  *   You've fallen into the habit/trap of setting all directories to 0777 which is a bad practice that will definitely frustrate or worry your security teams!
     *   If you want to be fairly permissive, then 0644 is more typical for directories (Read/write for owner, read for everyone) but since we're specifying the owner/group here, maybe we should be more restricted like 0640 - definitely worth testing and checking I haven't missed a permission though!
     *   For the files, I don't think any of them should need execute permissions, so similar permissions (0644 or 0640 should suffice)

Possibly a consequence of my copying, but the indentation also potentially looks out - we want all of our tasks to be part of a single tasks array, so rather than:

  tasks:
  - name: Install Git
    become: yes
...

  tasks:
  - name: Create a directory
    become: yes
...

more like:

  tasks:
  - name: Install Git
    become: yes
...

  - name: Create a directory
    become: yes
...

Carefully making sure all the elements (designated with the -) are in line

—
Reply to this email directly, view it on GitHub<https://github.com/smellybeagle/DevOps-Course-Starter/pull/7#pullrequestreview-1624668302>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZIQGPMW3UBV7ATTMKY22WDX2G7FRANCNFSM6AAAAAA4UUYD7M>.
You are receiving this because you authored the thread.Message ID: ***@***.***>